import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const vaultPluginPath = "/Users/tom/Documents/obsidian/.obsidian/plugins/weekly-notes";

// Plugin to copy files to vault after build
const copyToVaultPlugin = {
    name: 'copy-to-vault',
    setup(build) {
        build.onEnd(async () => {
            try {
                await esbuild.build({
                    entryPoints: ["main.ts"],
                    bundle: true,
                    outfile: `${vaultPluginPath}/main.js`,
                    ...commonConfig
                });

                // Copy manifest.json manually
                const fs = await import('fs/promises');
                await fs.copyFile('manifest.json', `${vaultPluginPath}/manifest.json`);

                console.log(`\n\x1b[32m[OK]\x1b[0m Copied to ${vaultPluginPath}`);
            } catch (e) {
                console.error("Failed to copy to vault:", e);
            }
        });
    },
};

const commonConfig = {
    banner: {
        js: banner,
    },
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
};

const context = await esbuild.context({
    entryPoints: ["main.ts"],
    bundle: true,
    outfile: "main.js",
    plugins: [copyToVaultPlugin], // Add the copy plugin
    ...commonConfig
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
